#! /usr/bin/env python
# coding=utf-8

'''
tunetctl: TUNet CLI
Command line tool for Tsinghua University net login
by SyiMyuZya <syimyuzya@gmail.com>
'''

from __future__ import print_function, unicode_literals

import json
import os
import sys

from getopt import gnu_getopt, GetoptError
from getpass import getpass
from md5 import md5
from urllib import urlencode
from urllib2 import urlopen

try:
    import readline
except ImportError:
    pass


########

# URLs

URL_LOGIN = 'http://net.tsinghua.edu.cn/cgi-bin/do_login'
URL_LOGOUT = 'http://net.tsinghua.edu.cn/cgi-bin/do_logout'


########

# utilities

def check():
    '''
    Get online information of this connection.
    '''
    return urlopen(URL_LOGIN, b'action=check_online').read().split(',')

def login(username, password):
    '''
    Login with username and password(encrypted).
    
    This function does not need the raw password.
    '''
    return urlopen(URL_LOGIN, urlencode({
        'username':username,
        'password':password,
        'drop':'0',
        'type':'1',
        'n':'100'
    })).read()

def logout():
    '''
    Logout.
    '''
    return urlopen(URL_LOGOUT, b'').read()


########

# interface

def show_version():
    print('TUNet Command Line Tool',
          'version 0.0.1',
          '',
          'by SyiMyuZya <syimyuzya@gmail.com>',
          sep='\n',
          file=sys.stderr)

def show_usage():
    show_version()
    print('',
          'Usage:',
          ' no option:',
          '  Show the current connect status of this device.',
          ' -l --login:',
          '  Login. Will prompt input for username and password.',
          ' -o --logout:',
          '  Logout.',
          ' -f <file> --file=<file>',
          '  Login with identity file <file>.',
          ' -s <file> --save=<file>',
          '  Login and save the identity info to <file>.',
          ' -d --default',
          '  Login with the default identity file.(~/.tunet)',
          ' -h --help',
          '  Print this message.',
          sep='\n',
          file=sys.stderr)

def show_status(**opt):
    print('Current status:')
    status = check()
    if len(status)==1:
        print('  Not logged in.')
    else:
        print('  User: '+status[1],
              '  Usage: '+status[2]+'B',
              '  Time: '+status[4]+'s',
              '  (Unknown arg0): '+status[0],
              '  (Unknown arg3): '+status[3],
              sep='\n')

def do_login(**opt):
    if opt.has_key('file'):
        user = json.load(open(opt['file']))
    else:
        user = {}
        print('User: ', end='')
        user['name'] = raw_input()
        user['pass'] = md5(getpass()).hexdigest()
    if opt.has_key('save'):
        json.dump(user, open(opt['save'], 'w'))
    res = login(user['name'], user['pass'])
    print('Server response:', res)
    show_status()

def do_logout(**opt):
    res = logout()
    print('Server response:', res)

def main():
    try:
        opts, args = gnu_getopt(sys.argv[1:], 'hlof:s:d',
                ['help', 'login', 'logout', 'file=', 'save=', 'default'])
        if len(args):
            raise GetoptError('unexpected argument '+args[0])
        actions = set()
        options = {}
        for opt in opts:
            if opt[0]=='-h' or opt[0]=='--help':
                actions.add('help')
            if opt[0]=='-l' or opt[0]=='--login':
                actions.add('login')
            if opt[0]=='-o' or opt[0]=='--logout':
                actions.add('logout')
            if opt[0]=='-f' or opt[0]=='--file':
                actions.add('login')
                options['file'] = opt[1]
            if opt[0]=='-s' or opt[0]=='--save':
                actions.add('login')
                options['save'] = opt[1]
            if opt[0]=='-d' or opt[0]=='--default':
                actions.add('login')
                options['file'] = os.path.join(os.path.expanduser('~'), '.tunet')
        if len(actions)==0:
            show_status()
        elif len(actions)>1:
            raise GetoptError('can not perform multiple actions: '
                    +repr(list(actions)))
        else:
            {'help':show_usage,
             'login':do_login,
             'logout':do_logout}[next(iter(actions))](**options)
    except GetoptError as e:
        print('Err: '+e.msg,
              'Use -h(--help) for help',
              sep='\n', file=sys.stderr)
    except KeyboardInterrupt:
        print('Canceled', file=sys.stderr)

if __name__=='__main__':
    main()

# vim: ts=4 sw=4 et
